Repository ftn-dnb/ktsnwt, pull requests merged in 2020-01, with the labels that each got.

#45 Test/e2e login registration
  ktsnwt-client/src/app/components/login/login.component.html
  ktsnwt-client/src/app/components/registration/registration.component.html
  ktsnwt-client/src/app/components/toolbar/toolbar.component.html
  ktsnwt-e2e-testing/src/main/java/rs/ac/uns/ftn/ktsnwt/pages/HomePage.java
  ktsnwt-e2e-testing/src/main/java/rs/ac/uns/ftn/ktsnwt/pages/LoginPage.java
  ktsnwt-e2e-testing/src/main/java/rs/ac/uns/ftn/ktsnwt/pages/RegistrationPage.java
  ktsnwt-e2e-testing/src/test/java/rs/ac/uns/ftn/ktsnwt/e2e/LoginTest.java
  ktsnwt-e2e-testing/src/test/java/rs/ac/uns/ftn/ktsnwt/e2e/RegistrationTest.java
  ktsnwt-e2e-testing/src/test/java/rs/ac/uns/ftn/ktsnwt/e2e/config/Constants.java
Labels: enhancement

#46 Test/e2e user settings
  ktsnwt-client/src/app/components/toolbar/toolbar.component.html
  ktsnwt-client/src/app/components/user-settings/user-settings.component.html
  ktsnwt-e2e-testing/src/main/java/rs/ac/uns/ftn/ktsnwt/pages/HomePage.java
  ktsnwt-e2e-testing/src/main/java/rs/ac/uns/ftn/ktsnwt/pages/UserSettingsPage.java
  ktsnwt-e2e-testing/src/test/java/rs/ac/uns/ftn/ktsnwt/e2e/UserSettingsTest.java
  ktsnwt-e2e-testing/src/test/java/rs/ac/uns/ftn/ktsnwt/e2e/config/Constants.java
Labels: enhancement

#51 Add tests for CustomUserDetailsService and AuthenticationController.
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/constants/SecurityContextConstants.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/constants/TestHttpServletRequest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/constants/UserConstants.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/controller/AuthencticationControllerIntegrationTest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/controller/suites/ControllerIntegrationTests.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/suites/ServiceIntegrationTests.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/suites/ServiceUnitTests.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/userDetails/CustomUserDetailsServiceIntegrationTest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/userDetails/CustomUserDetailsServiceUnitTest.java
Labels: enhancement

#56 Add location client functionality. Minor fixes in service.
  ktsnwt-client/package-lock.json
  ktsnwt-client/package.json
  ktsnwt-client/src/app/app-routing.module.ts
  ktsnwt-client/src/app/app.module.ts
  ktsnwt-client/src/app/components/admin/add-location/add-location.component.css
  ktsnwt-client/src/app/components/admin/add-location/add-location.component.html
  ktsnwt-client/src/app/components/admin/add-location/add-location.component.ts
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.css
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.html
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.ts
  ktsnwt-client/src/app/components/locations/locations.component.html
  ktsnwt-client/src/app/components/locations/locations.component.ts
  ktsnwt-client/src/app/config/api-paths.ts
  ktsnwt-client/src/app/config/router-paths.ts
  ktsnwt-client/src/app/services/location.service.ts
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/location/LocationServiceImpl.java
Labels: bug, enhancement

#58 Feature/buy ticket
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/controller/TicketController.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsService.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceImpl.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/constants/TicketConstants.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/controller/TicketControllerIntegrationTest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceImplIntegrationTest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceUnitTest.java
  ktsnwt-service/src/test/resources/import.sql
Labels: enhancement

#61 Feature/buy ticket paypal
  ktsnwt-client/src/app/app.module.ts
  ktsnwt-client/src/app/components/my-reservations/my-reservations.component.html
  ktsnwt-client/src/app/components/my-reservations/my-reservations.component.ts
  ktsnwt-client/src/app/components/paypal/paypal.component.html
  ktsnwt-client/src/app/components/paypal/paypal.component.ts
  ktsnwt-client/src/app/config/api-paths.ts
  ktsnwt-client/src/app/material.ts
  ktsnwt-client/src/app/models/ticket-buying-data.ts
  ktsnwt-client/src/app/services/ticket.service.spec.ts
  ktsnwt-client/src/app/services/ticket.service.ts
  ktsnwt-client/src/index.html
Labels: enhancement

#69 Add seating charts for sector modification. Add hall and sector addit…
  ktsnwt-client/angular.json
  ktsnwt-client/package-lock.json
  ktsnwt-client/package.json
  ktsnwt-client/src/app/app-routing.module.ts
  ktsnwt-client/src/app/app.module.ts
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.css
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.html
  ktsnwt-client/src/app/components/admin/edit-location/edit-location.component.ts
  ktsnwt-client/src/app/components/admin/hall-settings/hall-settings.component.css
  ktsnwt-client/src/app/components/admin/hall-settings/hall-settings.component.html
  ktsnwt-client/src/app/components/admin/hall-settings/hall-settings.component.ts
  ktsnwt-client/src/app/components/locations/locations.component.html
  ktsnwt-client/src/app/config/api-paths.ts
  ktsnwt-client/src/app/config/router-paths.ts
  ktsnwt-client/src/app/directives/seating.directive.ts
  ktsnwt-client/src/app/services/location.service.ts
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/sector/SectorServiceImpl.java
  ktsnwt-service/src/main/resources/import.sql
Labels: bug, enhancement

#71 Add and fix route guards.
  ktsnwt-client/src/app/app-routing.module.ts
  ktsnwt-client/src/app/services/auth/auth-login.guard.spec.ts
  ktsnwt-client/src/app/services/auth/auth-login.guard.ts
Labels: bug

#72 Modify api to return tickets by event day id.
  ktsnwt-client/src/app/components/admin/hall-settings/hall-settings.component.html
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/controller/TicketController.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/repository/TicketRepository.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsService.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceImpl.java
  ktsnwt-service/src/main/resources/import.sql
Labels: enhancement

#73 otkazivanje rezervacije
  ktsnwt-client/src/app/components/my-reservations/my-reservations.component.ts
  ktsnwt-client/src/app/config/api-paths.ts
  ktsnwt-client/src/app/models/address.ts
  ktsnwt-client/src/app/models/ticket.ts
  ktsnwt-client/src/app/services/my-reservations.service.spec.ts
  ktsnwt-client/src/app/services/my-reservations.service.ts
  ktsnwt-client/src/app/services/ticket.service.ts
Labels: enhancement

#75 fix/pageable-locations-frontend
  ktsnwt-client/src/app/components/locations/locations.component.ts
  ktsnwt-client/src/app/components/my-reservations/my-reservations.component.ts
  ktsnwt-client/src/app/models/response/address.ts
  ktsnwt-client/src/app/models/response/hall.ts
  ktsnwt-client/src/app/models/response/location.ts
  ktsnwt-client/src/app/models/response/sector.ts
  ktsnwt-client/src/app/models/response/ticket.ts
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/controller/LocationController.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/mappers/LocationMapper.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/repository/LocationRepository.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/location/LocationService.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/location/LocationServiceImpl.java
Labels: bug

#76 fix/my-tickets-pageable
  .idea/workspace.xml
  ktsnwt-client/src/app/components/my-reservations/my-reservations.component.ts
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/controller/TicketController.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/mappers/TicketMapper.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsService.java
  ktsnwt-service/src/main/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceImpl.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceImplIntegrationTest.java
  ktsnwt-service/src/test/java/rs/ac/uns/ftn/ktsnwt/service/tickets/TicketsServiceUnitTest.java
Labels: bug
